// Copyright 2023 @crocogene
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef OLED_DISPLAY_128X64

#define USE_SERIAL
#define MASTER_LEFT
#define SPLIT_LAYER_STATE_ENABLE

#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_ALTERNATING
